/*Generated by SharpKit 5 v5.01.1000*/
if (typeof($CreateException)=='undefined') 
{
    var $CreateException = function(ex, error) 
    {
        if(error==null)
            error = new Error();
        if(ex==null)
            ex = new System.Exception.ctor();       
        error.message = ex.message;
        for (var p in ex)
           error[p] = ex[p];
        return error;
    }
}
if (typeof(SharpAlg) == "undefined")
    var SharpAlg = {};
if (typeof(SharpAlg.Native) == "undefined")
    SharpAlg.Native = {};
if (typeof(SharpAlg.Native.Builder) == "undefined")
    SharpAlg.Native.Builder = {};
SharpAlg.Native.Builder.ExprBuilderFactory = function ()
{
};
SharpAlg.Native.Builder.ExprBuilderFactory.CreateDefault = function ()
{
    return new SharpAlg.Native.Builder.ConvolutionExprBuilder(SharpAlg.Native.ContextFactory.Default);
};
SharpAlg.Native.Builder.ExprBuilderFactory.CreateEmpty = function ()
{
    return new SharpAlg.Native.Builder.ConvolutionExprBuilder(SharpAlg.Native.ContextFactory.Empty);
};
SharpAlg.Native.Builder.ExprBuilderFactory.Create = function (context)
{
    return new SharpAlg.Native.Builder.ConvolutionExprBuilder(context);
};
if (typeof(JsTypes) == "undefined")
    var JsTypes = [];
var SharpAlg$Native$ContextFactory =
{
    fullname: "SharpAlg.Native.ContextFactory",
    baseTypeName: "System.Object",
    staticDefinition:
    {
        CreateEmpty: function ()
        {
            return new SharpAlg.Native.Context.ctor();
        },
        CreateDefault: function ()
        {
            return new SharpAlg.Native.Context.ctor().Register$$Function(SharpAlg.Native.Functions.get_Factorial()).Register$$Function(SharpAlg.Native.Functions.get_Ln()).Register$$Function(SharpAlg.Native.Functions.get_Diff()).Register$$Function(SharpAlg.Native.Functions.get_Exp()).Register$$Function(SharpAlg.Native.Functions.get_Pi()).Register$$Function(SharpAlg.Native.Functions.get_Sin()).Register$$Function(SharpAlg.Native.Functions.get_Cos());
        },
        cctor: function ()
        {
            SharpAlg.Native.ContextFactory.Empty = null;
            SharpAlg.Native.ContextFactory.Default = null;
            SharpAlg.Native.ContextFactory.Default = SharpAlg.Native.ContextFactory.CreateDefault();
            SharpAlg.Native.ContextFactory.Default.set_ReadOnly(true);
            SharpAlg.Native.ContextFactory.Empty = SharpAlg.Native.ContextFactory.CreateEmpty();
            SharpAlg.Native.ContextFactory.Empty.set_ReadOnly(true);
        }
    },
    assemblyName: "SharpAlg",
    Kind: "Class",
    definition:
    {
        ctor: function ()
        {
            System.Object.ctor.call(this);
        }
    }
};
JsTypes.push(SharpAlg$Native$ContextFactory);
var SharpAlg$Native$ExpressionExtensions =
{
    fullname: "SharpAlg.Native.ExpressionExtensions",
    baseTypeName: "System.Object",
    staticDefinition:
    {
        Evaluate: function (expr, context)
        {
            return expr.Visit$1(SharpAlg.Native.Number.ctor, new SharpAlg.Native.ExpressionEvaluator((context != null ? context : SharpAlg.Native.ContextFactory.Default)));
        },
        Diff: function (expr, parameterName)
        {
            return SharpAlg.Native.ImplementationExpressionExtensions.Diff(expr, SharpAlg.Native.Builder.ExprBuilderFactory.CreateDefault(), parameterName);
        },
        Print: function (expr, context)
        {
            return expr.Visit$1(System.String.ctor, SharpAlg.Native.Printer.ExpressionPrinter.Create((context != null ? context : SharpAlg.Native.ContextFactory.Default)));
        },
        Parse: function (expression, builder)
        {
            return SharpAlg.Native.ExpressionExtensions.GetExpression(SharpAlg.Native.ExpressionExtensions.ParseCore(expression, (builder != null ? builder : SharpAlg.Native.Builder.ExprBuilderFactory.CreateDefault())));
        },
        GetExpression: function (parser)
        {
            if (parser.errors.Count > 0)
                throw $CreateException(new System.InvalidOperationException.ctor$$String("String can not be parsed"), new Error());
            return parser.Expr;
        },
        ParseCore: function (expression, builder)
        {
            var scanner = new SharpAlg.Native.Parser.Scanner.ctor(expression);
            var parser = new SharpAlg.Native.Parser.Parser(scanner, builder);
            parser.Parse();
            return parser;
        }
    },
    assemblyName: "SharpAlg",
    Kind: "Class",
    definition:
    {
        ctor: function ()
        {
            System.Object.ctor.call(this);
        }
    }
};
JsTypes.push(SharpAlg$Native$ExpressionExtensions);
var SharpAlg$Native$Functions =
{
    fullname: "SharpAlg.Native.Functions",
    baseTypeName: "System.Object",
    staticDefinition:
    {
        cctor: function ()
        {
            SharpAlg.Native.Functions.factorial = null;
            SharpAlg.Native.Functions.ln = null;
            SharpAlg.Native.Functions.diff = null;
            SharpAlg.Native.Functions.exp = null;
            SharpAlg.Native.Functions.pi = null;
            SharpAlg.Native.Functions.sin = null;
            SharpAlg.Native.Functions.cos = null;
        },
        Factorial$$: "SharpAlg.Native.Function",
        get_Factorial: function ()
        {
            return (SharpAlg.Native.Functions.factorial != null ? SharpAlg.Native.Functions.factorial : (SharpAlg.Native.Functions.factorial = new SharpAlg.Native.FactorialFunction.ctor()));
        },
        Ln$$: "SharpAlg.Native.Function",
        get_Ln: function ()
        {
            return (SharpAlg.Native.Functions.ln != null ? SharpAlg.Native.Functions.ln : (SharpAlg.Native.Functions.ln = new SharpAlg.Native.LnFunction.ctor()));
        },
        Diff$$: "SharpAlg.Native.Function",
        get_Diff: function ()
        {
            return (SharpAlg.Native.Functions.diff != null ? SharpAlg.Native.Functions.diff : (SharpAlg.Native.Functions.diff = new SharpAlg.Native.DiffFunction.ctor()));
        },
        Exp$$: "SharpAlg.Native.Function",
        get_Exp: function ()
        {
            return (SharpAlg.Native.Functions.exp != null ? SharpAlg.Native.Functions.exp : (SharpAlg.Native.Functions.exp = new SharpAlg.Native.ExpFunction.ctor()));
        },
        Pi$$: "SharpAlg.Native.Function",
        get_Pi: function ()
        {
            return (SharpAlg.Native.Functions.pi != null ? SharpAlg.Native.Functions.pi : (SharpAlg.Native.Functions.pi = new SharpAlg.Native.PiFunction.ctor()));
        },
        Sin$$: "SharpAlg.Native.Function",
        get_Sin: function ()
        {
            return (SharpAlg.Native.Functions.sin != null ? SharpAlg.Native.Functions.sin : (SharpAlg.Native.Functions.sin = new SharpAlg.Native.SinFunction.ctor()));
        },
        Cos$$: "SharpAlg.Native.Function",
        get_Cos: function ()
        {
            return (SharpAlg.Native.Functions.cos != null ? SharpAlg.Native.Functions.cos : (SharpAlg.Native.Functions.cos = new SharpAlg.Native.CosFunction.ctor()));
        }
    },
    assemblyName: "SharpAlg",
    Kind: "Class",
    definition:
    {
        ctor: function ()
        {
            System.Object.ctor.call(this);
        }
    }
};
JsTypes.push(SharpAlg$Native$Functions);
